### ISSUE TITLE
Signup now has different behavior than before

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#109]
This is probably FAD, but just checking.  Previously, after signing up:
1. you had the Training Modules first thing, and you couldn't see the Dashboard until you had watched those.  That is not happening any more
2. there was a questionnaire asking for your job, school, etc.  I don't see that any more either.

One minute video of the signup process.  Using Edge, Windows 10:
https://drive.google.com/file/d/1ewca5gmvslD3tMX15Zn_q2Jn456OOHkT/view?usp=drivesdk

**Comment by sharifyounes** [comment]
This is intentional

**Comment by lgutro** [comment]
Thanks!
