### ISSUE TITLE
iPad possibly displayed incorrectly

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#121]
This is probably too early to test.  But I'm working on a test to display different screen sizes and I noticed iPad doesn't look right.  I don't know if this will correlate to real iPad experience though.

If the new layout is ready to go and this still happens, and you are interested, I will look on a real iPad in the cloud to see if this is a real problem.

![Capture](https://user-images.githubusercontent.com/38503093/55185157-23c4e400-516a-11e9-89ed-86f3b464bdf2.JPG)

Also firefox doesn't look right in iPhone 5 dimensions.  Optimal Work logo is over everything.
![image](https://user-images.githubusercontent.com/38503093/55186167-448e3900-516c-11e9-924d-09cc8adf9045.png)

**Comment by sharifyounes** [comment]
Yeah, the new layout is more or less ready to go... (I hope)

**Comment by lgutro** [comment]
#1) The iPad size I had is very old.  New iPad size is different.  There seems to be some big problem everywhere now (see below) so I will test it with the new size when things get better.

#2)The firefox issue, if it's real, was there before this change.  

![image](https://user-images.githubusercontent.com/38503093/55187378-473e5d80-516f-11e9-90a1-664657301128.png)

**Comment by sharifyounes** [comment]
That looks like it's not loading any CSS.

**Comment by lgutro** [comment]
The older iPad dimensions look OK now.  The firefox I still see, but this is only on my Windows screen resized.  I would need a real iPhone 5 device with firefox on it to prove it, which I don't have.
