### ISSUE TITLE
After 9 pm the dashboard and GH page do not update

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#126]
Sometime roughly after 9 pm, the GH status does not update.  

I have a goal of 2 GH's per day.  I completed my second GH after 9 pm and:
1) the star in the  main dashboard did not get filled in 
2) the message that I had completed my goal for the day, etc. was not seen

If I click 'Tools' 'Golden Hours':
1) the number was still 1
2) the graph showed 1
3) the new GH did show as completed in the history section
I was a bit worried that I had broken my 'streak'.

The next day however, the streak was unbroken, and the graph showed 2.

Maybe this is done on purpose to discourage working past 9?
But in that case, shouldn't a) we be warned somewhere about the end time and b) the streak should be broken and the GH's not show in the graph the next day c) some people work 2nd/3rd shift and this wouldn't be good for them.

**Comment by sharifyounes** [comment]
I think this is fixed :) I guess we'll have to wait till 9pm to see...

**Comment by lgutro** [comment]
In the building site, it's not updating the total number of GH's correctly.  I did a couple of GH's @ 8:20-8:30 and the number is not updating.
https://drive.google.com/file/d/1TD_Wq_NUbxURqCuhKnz1lu008QXu-zZh/view?usp=drivesdk

In the real site, it is fixed!!

**Comment by lgutro** [comment]
Fixed in real site
