### ISSUE TITLE
Find a good automation language/mobile farm for e2e testing

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#29]
Investigating good tools for automating angular js that I can use with Kobiton or similar inexpensive cloud mobile farm

https://github.com/Innovic-io/katalon-angular

https://innovic.io/services.html

http://appium.io/docs/en/writing-running-appium/web/mobile-web/

![capture](https://user-images.githubusercontent.com/38503093/52136241-99eb1580-2615-11e9-862a-7f027234e264.JPG)

**Comment by lgutro** [comment]
Would it be possible to add formcontrolname to the 'Steps' textarea ?

**Comment by lgutro** [comment]
Hi @sharifyounes - Would it be possible to add an 'id' or 'formcontrolname'  to the 'Steps' textarea ?

**Comment by sharifyounes** [comment]
Done

**Comment by sharifyounes** [comment]
added id="question-text"

**Comment by lgutro** [comment]
Based on this: https://adtmag.com/blogs/dev-watch/2017/05/device-clouds.aspx and seeing CrossBrowserTesting and BrowserStack, I think Kobiton is the best value.  If I had more money, CrossBrowserTesting has more/better features for automation.

**Comment by lgutro** [comment]
For language/framework:  python/robotframework:

Python automation site
https://github.com/atinfo/awesome-test-automation/blob/master/python-test-automation.md

Looks like the best is Robot Framework
Robot Framework in python with RIDE: 

https://github.com/fkromer/awesome-robotframework says Robot Framework contains AngularJS library

With both AngularJS 1.0 and 2.0 tested. Very active
https://github.com/Selenium2Library/robotframework-angularjs

There is a not-too-active cross-browser library:
https://github.com/luisxiaomai/robotframework-anywherelibrary

AnywhereLibrary is a cross platform (desktop browser, Android, iOS) testing library for Robot Framework that leverages the Selenium 2 (WebDriver) libraries internally to control a web browser and Appium as mobile test automation framework for use with native and hybrid apps.

This library is especially suitable for handling SPA (single-page apps) with responsive design patterns. With this you only need to generate a set of scripts to cover all platforms (desktop browser, Android, iOS).

Finally, the following link has robotframework/python/kobiton automation framework ready to go. Active.
https://github.com/kobiton/samples

**Comment by lgutro** [comment]
https://stackoverflow.com/questions/27938972/robotframework-vs-protractor-for-angularjs-testing
