### ISSUE TITLE
Can't see text field in GH Challenge tab when click on Other, Galaxy

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#33]
Testing on Kobiton on Galaxy Prime J7 Android 6.0, 1020x1920

During Golden Hour, Challenge tab, when I click on Other, the keypad comes up and I can't see the text field.  Once I type, I do see it.

https://drive.google.com/file/d/1Wb50R2QvAgauBTX7YKRqWHmVpm18YJ9V/view?usp=drivesdk

**Comment by sharifyounes** [comment]
I think this is okay..
