### ISSUE TITLE
Edge and iOS Chrome give 500 error

### ISSUE THREAD

**Issue by lgutro** [lgutro/hello-world#83]
Edge right now works for the regular optimal work site, but give a 500 page error now.  This is also seen in iOS 11 Chrome.

I am trying to go to http://building.optimalwork.com and it goes here

![capture](https://user-images.githubusercontent.com/38503093/53689118-65ee3780-3d1c-11e9-882f-65fb7224e247.JPG)

**Comment by lgutro** [comment]
Also tried both https and http.

**Comment by lgutro** [comment]
I am now seeing this for headlesschrome in automation.

**Comment by lgutro** [comment]
iOS 11 Safari, Firefox, and Edge issues do not happen on the real site any more so this can be closed.

However @sharifyounes do you know why I keep getting this on the building site?  It happened last night twice, once at 1:00 AM.

![capture](https://user-images.githubusercontent.com/38503093/53882194-a6330b80-3fe3-11e9-896d-2e72c0ea4f2f.JPG)

**Comment by sharifyounes** [comment]
What page was it on? /log-out?

**Comment by lgutro** [comment]
/login

Lisa

> On Mar 6, 2019, at 3:50 PM, Sharif Younes <notifications@github.com> wrote:
> 
> What page was it on? /log-out?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
Study Reveals What Just A Single Diet Soda Does To Your...
nucific.com
http://thirdpartyoffers.juno.com/TGL3131/5c8137205463c371f463bst03duc

**Comment by lgutro** [comment]
@sharifyounes It is /login.  It happened 2 out of 5 attempts:

![capture](https://user-images.githubusercontent.com/38503093/53968017-4bbdac00-40c4-11e9-9209-2ea65857bf88.JPG)

**Comment by sharifyounes** [comment]
Great question, I don't know why. Was there anything different about the request?

I didn't have great logs set up on building, but I just set them up, so if it happens again I can check the logs and (hopefully) figure it out!

**Comment by lgutro** [comment]
Hi @sharifyounes.   It happened @11:39 am today.  

Lisa

> On Mar 7, 2019, at 11:33 AM, Sharif Younes <notifications@github.com> wrote:
> 
> Great question, I don't know why. Was there anything different about the request?
> 
> I didn't have great logs set up on building, but I just set them up, so if it happens again I can check the logs and (hopefully) figure it out!
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
Our Hearts Go Out To Jennifer Lopez
go.dedicatedoffers.com
http://thirdpartyoffers.juno.com/TGL3131/5c815036a523f50355abcst03vuc
